### ISSUE TITLE
Allow to disable beats_security even with full stack

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-beats#102]
Activating beats security when using the full stack is a great idea. But we need to be able to still override it and disable `beats_security` even when the rest is active. Or we decide against it. But I had a case where certificate handling was broken and I needed to disable it manually.

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
