### ISSUE TITLE
Fix name in Readme

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-beats#13]
When merging this role with our old `filebeat` one, we accidentally took the old name into `README.md`. We need to change it to `Beats`.

**Comment by aditya28sarin** [comment]
Can you assign me this issue?

**Comment by widhalmt** [comment]
@aditya28sarin Yes, done. Let me know if you need help with creating the Pull Request.

**Comment by widhalmt** [comment]
@aditya28sarin didn't react to change requests. So I will contribute the change myself.
