### ISSUE TITLE
Overhaul Beats setup

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-beats#48]
We should make sure that we:

* Only run `*beat setup` once (more specific: on one host per run)
* Create our "lockfile" to not rerun the task with a version specific name, so we can rerun it after an update

Note: Rerunning `setup` doesn't hurt (save for taking long) so we don't need to make extra sure that it is not rerun. That's especially true if this role manages setup and the pipelines all by its own

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
