### ISSUE TITLE
Create verify task for specific version installation

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-beats#83]
We have some checks in `verify.yml` in the `peculiar` scenario within molecule. It seems not as easy as I thought to match the string. I'm thinking of thing like we have in https://github.com/NETWAYS/ansible-role-logstash/blob/master/molecule/specific_version/verify.yml . Unfortunately filebeat has some extra information in the same line and matching gives me a hard time. So if anyone has an idea about how to easily match - I'd happy to use it.

I know, I could find some but I did a check with the debug variable and the role works as expected. And honestly I'm running out of motivation just for the test.

**Comment by DanOPT** [comment]
Error if stdout_lines is used:
> ./molecule/peculiar/verify.yml
>   Error: 18:61 [new-line-at-end-of-file] no new line character at the end of file

If only stdout is used the checks pass. I' not sure but it seems to me Ansible is expecting a second line if stdout_lines is used, but the value is only one line?

Anyway. It's working now.

**Comment by widhalmt** [comment]
Good catch! I'll have a look at your fix. Thank you very much for contributing!
